### PR TITLE
Awesome books: with ES6

### PR DESCRIPTION
**Pull request by banlon-jones**
# Awesome books: with ES6
- We added the `module` directory
- added the `display` and `book` modules
- added the appImage.png file
- added the npm packages 
- and used ES6 Syntax

NB: Do `npm i` to install all project dependencies

### CODE REVIEW

**Review by omar-labana — CHANGES_REQUESTED** [review]
Hi @banlon-jones, 

You have implemented all the required features correctly with no errors or bugs. ✔️ 
There are one case that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Please, omit the usage of the `function` keyword to initialize/declare a function handler across your codebase instead, use the arrow functions `const fname =  ( args ) => { }` to do so.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by banlon-jones** [comment]
Hi @omar-labana 
`Please, omit the usage of the function keyword to initialize/declare a function handler across your codebase instead, use the arrow functions const fname = ( args ) => { } to do so.` this is not a project requirement but rather a suggestion you didn't tell me why not to use the `function` keyword

**Review by elyor-doniyorov — APPROVED** [review]
Hi @banlon-jones👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by GzimAsani — COMMENTED** [review]
Hi @mprotic123 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is already approved and merged.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
